skip: >
  $CIRRUS_COMMIT_MESSAGE =~ '.*\[cirrus:skip\].*' ||
  $CIRRUS_COMMIT_MESSAGE =~ '.*\[skip ci\].*' ||
  $CIRRUS_COMMIT_MESSAGE =~ '.*\[ci skip\].*'

container:
  dockerfile: Dockerfile
  cpu: 8
  memory: 32G

build_task:
  name: Build IronFox
  only_if: >
    $CIRRUS_BRANCH == "main" ||
    $CIRRUS_BRANCH =~ ".*--ci-incl$"
  timeout_in: 120m
  env:
    SB_GAPI_KEY: ENCRYPTED[!3da25d528d0c34be6d3f3bbe73d2cbce960b8e55ed7b54906a1140b4929032b026a1ea5f0876fe46b0f0044711cc08bd!]
    SB_GAPI_KEY_FILE: /opt/sb-gapi.data
    ANDROID_HOME: /root/android-sdk
    ANDROID_NDK: /root/android-sdk/ndk/27.2.12479018
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    matrix:
      - VERSION_NAME: "134.0"
        VERSION_CODE: 31340000
      - VERSION_NAME: "134.0"
        VERSION_CODE: 31340020
  sb_gapi_script: mkdir -p "$(dirname "${SB_GAPI_KEY_FILE}")" && echo "${SB_GAPI_KEY}" > "${SB_GAPI_KEY_FILE}"
  sources_script: bash ./scripts/get_sources.sh
  build_script: bash ./scripts/ci-build.sh
  apk_artifacts:
    path: gecko/mobile/android/fenix/app/build/outputs/apk/fenix/release/*.apk
  aab_artifacts:
    path: gecko/mobile/android/fenix/app/build/outputs/bundle/fenixRelease/*.aab
