from itertools import groupby
from operator import itemgetter
from pathlib import Path
import re
from typing import Callable, Dict, List

from common.paths import Paths
from execution.definition import BuildDefinition, TaskDefinition
from execution.find_replace import regex
from execution.types import ReplacementAction


# Files and directories to exclude (matches the shell function behavior)
_EXCLUDED_DIRS = {"androidTest", "docs", "test", "tests"}
_EXCLUDED_EXTS = {".json", ".md", ".swift"}


def _should_skip(path: Path) -> bool:
    if path.suffix in _EXCLUDED_EXTS:
        return True

    for part in path.parts:
        if part in _EXCLUDED_DIRS:
            return True

    return False


def noop_moz_endpoints(
    d: BuildDefinition,
    dir: Path,
    endpoints: List[str],
    task_name: str = "",
) -> List[TaskDefinition]:
    escaped = [re.escape(endpoint) for endpoint in endpoints]
    patterns = []
    for esc in escaped:
        patterns.extend(
            [
                (rf'"{esc}[^"\']*"', r'""'),
                (rf"'{esc}[^\"']*'", r"''"),
                (rf'"{esc}/[^"\']*"', r'""'),
                (rf"'{esc}/[^\"']*'", r"''"),
                (rf'"{esc}\.[^"\']*"', r'""'),
                (rf"'{esc}\.[^\"']*'", r"''"),
                (rf'"http://{esc}[^"\']*"', r'""'),
                (rf"'http://{esc}[^\"']*'", r"''"),
                (rf'"http://{esc}/[^"\']*"', r'""'),
                (rf"'http://{esc}/[^\"']*'", r"''"),
                (rf'"http://{esc}\.[^"\']*"', r'""'),
                (rf"'http://{esc}\.[^\"']*'", r"''"),
                (rf'"https://{esc}[^"\']*"', r'""'),
                (rf"'https://{esc}[^\"']*'", r"''"),
                (rf'"https://{esc}/[^"\']*"', r'""'),
                (rf"'https://{esc}/[^\"']*'", r"''"),
                (rf'"https://{esc}\.[^"\']*"', r'""'),
                (rf"'https://{esc}\.[^\"']*'", r"''"),
            ]
        )

    all_replacements: List[ReplacementAction] = [
        regex(pat, repl) for pat, repl in patterns
    ]

    return d.find_replace_dir_tracked(
        name=(
            f"Remove endpoints: {dir.name}"
            if len(task_name.strip()) == 0
            else task_name
        ),
        dir=dir,
        replacements=all_replacements,
        batch_size=50,
        file_filter=lambda f: not _should_skip(f),
    )


def get_moz_endpoints(paths: Paths) -> Dict[Path, List[str]]:
    application_services = paths.application_services_dir
    mozilla_release = paths.firefox_dir
    glean = paths.glean_dir

    items = [
        # fmt:off
        ## AMO Discovery/recommendations
        ("discovery.addons.allizom.org", application_services  ),
        ("discovery.addons.allizom.org", mozilla_release / "mobile"),
        ("discovery.addons.allizom.org", mozilla_release / "modules"),
        ("discovery.addons.allizom.org", mozilla_release / "netwerk"),
        ("discovery.addons.allizom.org", mozilla_release / "python"),
        ("discovery.addons.allizom.org", mozilla_release / "toolkit"),
        ("discovery.addons.allizom.org", glean),
        ("discovery.addons.mozilla.org", application_services),
        ("discovery.addons.mozilla.org", mozilla_release / "mobile"),
        ("discovery.addons.mozilla.org", mozilla_release / "modules"),
        ("discovery.addons.mozilla.org", mozilla_release / "netwerk"),
        ("discovery.addons.mozilla.org", mozilla_release / "python"),
        ("discovery.addons.mozilla.org", mozilla_release / "toolkit"),
        ("discovery.addons.mozilla.org", glean),
        ("discovery.addons-dev.allizom.org", application_services),
        ("discovery.addons-dev.allizom.org", mozilla_release / "mobile"),
        ("discovery.addons-dev.allizom.org", mozilla_release / "modules"),
        ("discovery.addons-dev.allizom.org", mozilla_release / "netwerk"),
        ("discovery.addons-dev.allizom.org", mozilla_release / "python"),
        ("discovery.addons-dev.allizom.org", mozilla_release / "toolkit"),
        ("discovery.addons-dev.allizom.org", glean),
        
        ## ASan crash reporting
        ("anf1.fuzzing.mozilla.org", application_services),
        ("anf1.fuzzing.mozilla.org", mozilla_release / "mobile"),
        ("anf1.fuzzing.mozilla.org", mozilla_release / "modules"),
        ("anf1.fuzzing.mozilla.org", mozilla_release / "netwerk"),
        ("anf1.fuzzing.mozilla.org", mozilla_release / "python"),
        ("anf1.fuzzing.mozilla.org", mozilla_release / "toolkit"),
        ("anf1.fuzzing.mozilla.org", glean),
        
        ## Connectivity checks
        ("detectportal.firefox.com", application_services),
        ("detectportal.firefox.com", mozilla_release / "mobile"),
        ("detectportal.firefox.com", mozilla_release / "modules"),
        ("detectportal.firefox.com", mozilla_release / "netwerk"),
        ("detectportal.firefox.com", mozilla_release / "python"),
        ("detectportal.firefox.com", mozilla_release / "toolkit"),
        ("detectportal.firefox.com", glean),
        
        ## Contile
        ("contile.services.mozilla.com", application_services),
        ("contile.services.mozilla.com", mozilla_release / "mobile"),
        ("contile.services.mozilla.com", mozilla_release / "modules"),
        ("contile.services.mozilla.com", mozilla_release / "netwerk"),
        ("contile.services.mozilla.com", mozilla_release / "python"),
        ("contile.services.mozilla.com", mozilla_release / "toolkit"),
        ("contile.services.mozilla.com", glean),
        ("contile-images.services.mozilla.com", application_services),
        ("contile-images.services.mozilla.com", mozilla_release / "mobile"),
        ("contile-images.services.mozilla.com", mozilla_release / "modules"),
        ("contile-images.services.mozilla.com", mozilla_release / "netwerk"),
        ("contile-images.services.mozilla.com", mozilla_release / "python"),
        ("contile-images.services.mozilla.com", mozilla_release / "toolkit"),
        ("contile-images.services.mozilla.com", glean),
        
        ## Crash reporting
        ("crash-reports.allizom.org", application_services),
        ("crash-reports.allizom.org", mozilla_release / "mobile"),
        ("crash-reports.allizom.org", mozilla_release / "modules"),
        ("crash-reports.allizom.org", mozilla_release / "netwerk"),
        ("crash-reports.allizom.org", mozilla_release / "python"),
        ("crash-reports.allizom.org", mozilla_release / "toolkit"),
        ("crash-reports.allizom.org", glean),
        ("crash-reports.mozilla.com", application_services),
        ("crash-reports.mozilla.com", mozilla_release / "mobile"),
        ("crash-reports.mozilla.com", mozilla_release / "modules"),
        ("crash-reports.mozilla.com", mozilla_release / "netwerk"),
        ("crash-reports.mozilla.com", mozilla_release / "python"),
        ("crash-reports.mozilla.com", mozilla_release / "toolkit"),
        ("crash-reports.mozilla.com", glean),
        ("crash-reports-xpsp2.mozilla.com", application_services),
        ("crash-reports-xpsp2.mozilla.com", mozilla_release / "mobile"),
        ("crash-reports-xpsp2.mozilla.com", mozilla_release / "modules"),
        ("crash-reports-xpsp2.mozilla.com", mozilla_release / "netwerk"),
        ("crash-reports-xpsp2.mozilla.com", mozilla_release / "python"),
        ("crash-reports-xpsp2.mozilla.com", mozilla_release / "toolkit"),
        ("crash-reports-xpsp2.mozilla.com", glean),
        ("crash-stacks.mozilla.com", application_services),
        ("crash-stacks.mozilla.com", mozilla_release / "mobile"),
        ("crash-stacks.mozilla.com", mozilla_release / "modules"),
        ("crash-stacks.mozilla.com", mozilla_release / "netwerk"),
        ("crash-stacks.mozilla.com", mozilla_release / "python"),
        ("crash-stacks.mozilla.com", mozilla_release / "toolkit"),
        ("crash-stacks.mozilla.com", glean),
        ("crash-stats.allizom.org", application_services),
        ("crash-stats.allizom.org", mozilla_release / "mobile"),
        ("crash-stats.allizom.org", mozilla_release / "modules"),
        ("crash-stats.allizom.org", mozilla_release / "netwerk"),
        ("crash-stats.allizom.org", mozilla_release / "python"),
        ("crash-stats.allizom.org", mozilla_release / "toolkit"),
        ("crash-stats.allizom.org", glean),
        ("crash-stats.mozilla.com", application_services),
        ("crash-stats.mozilla.com", mozilla_release / "mobile"),
        ("crash-stats.mozilla.com", mozilla_release / "modules"),
        ("crash-stats.mozilla.com", mozilla_release / "netwerk"),
        ("crash-stats.mozilla.com", mozilla_release / "python"),
        ("crash-stats.mozilla.com", mozilla_release / "toolkit"),
        ("crash-stats.mozilla.com", glean),
        ("crash-stats.mozilla.org", application_services),
        ("crash-stats.mozilla.org", mozilla_release / "mobile"),
        ("crash-stats.mozilla.org", mozilla_release / "modules"),
        ("crash-stats.mozilla.org", mozilla_release / "netwerk"),
        ("crash-stats.mozilla.org", mozilla_release / "python"),
        ("crash-stats.mozilla.org", mozilla_release / "toolkit"),
        ("crash-stats.mozilla.org", glean),
        ("socorro.prod.webservices.mozgcp.net", application_services),
        ("socorro.prod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("socorro.prod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("socorro.prod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("socorro.prod.webservices.mozgcp.net", mozilla_release / "python"),
        ("socorro.prod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("socorro.prod.webservices.mozgcp.net", glean),
        ("socorro-collector.services.mozilla.com", application_services),
        ("socorro-collector.services.mozilla.com", mozilla_release / "mobile"),
        ("socorro-collector.services.mozilla.com", mozilla_release / "modules"),
        ("socorro-collector.services.mozilla.com", mozilla_release / "netwerk"),
        ("socorro-collector.services.mozilla.com", mozilla_release / "python"),
        ("socorro-collector.services.mozilla.com", mozilla_release / "toolkit"),
        ("socorro-collector.services.mozilla.com", glean),
        ("socorro-webapp.services.mozilla.com", application_services),
        ("socorro-webapp.services.mozilla.com", mozilla_release / "mobile"),
        ("socorro-webapp.services.mozilla.com", mozilla_release / "modules"),
        ("socorro-webapp.services.mozilla.com", mozilla_release / "netwerk"),
        ("socorro-webapp.services.mozilla.com", mozilla_release / "python"),
        ("socorro-webapp.services.mozilla.com", mozilla_release / "toolkit"),
        ("socorro-webapp.services.mozilla.com", glean),
        ("socorro-webapp-allizom.stage.mozaws.net", application_services),
        ("socorro-webapp-allizom.stage.mozaws.net", mozilla_release / "mobile"),
        ("socorro-webapp-allizom.stage.mozaws.net", mozilla_release / "modules"),
        ("socorro-webapp-allizom.stage.mozaws.net", mozilla_release / "netwerk"),
        ("socorro-webapp-allizom.stage.mozaws.net", mozilla_release / "python"),
        ("socorro-webapp-allizom.stage.mozaws.net", mozilla_release / "toolkit"),
        ("socorro-webapp-allizom.stage.mozaws.net", glean),
        ("talkback.mozilla.org", application_services),
        ("talkback.mozilla.org", mozilla_release / "mobile"),
        ("talkback.mozilla.org", mozilla_release / "modules"),
        ("talkback.mozilla.org", mozilla_release / "netwerk"),
        ("talkback.mozilla.org", mozilla_release / "python"),
        ("talkback.mozilla.org", mozilla_release / "toolkit"),
        ("talkback.mozilla.org", glean),
        ("talkback-public.mozilla.org", application_services),
        ("talkback-public.mozilla.org", mozilla_release / "mobile"),
        ("talkback-public.mozilla.org", mozilla_release / "modules"),
        ("talkback-public.mozilla.org", mozilla_release / "netwerk"),
        ("talkback-public.mozilla.org", mozilla_release / "python"),
        ("talkback-public.mozilla.org", mozilla_release / "toolkit"),
        ("talkback-public.mozilla.org", glean),
        ("talkback-reports.mozilla.org", application_services),
        ("talkback-reports.mozilla.org", mozilla_release / "mobile"),
        ("talkback-reports.mozilla.org", mozilla_release / "modules"),
        ("talkback-reports.mozilla.org", mozilla_release / "netwerk"),
        ("talkback-reports.mozilla.org", mozilla_release / "python"),
        ("talkback-reports.mozilla.org", mozilla_release / "toolkit"),
        ("talkback-reports.mozilla.org", glean),
        
        ## DoH canary requests
        ("sitereview.zscaler.com", application_services),
        ("sitereview.zscaler.com", mozilla_release / "mobile"),
        ("sitereview.zscaler.com", mozilla_release / "modules"),
        ("sitereview.zscaler.com", mozilla_release / "netwerk"),
        ("sitereview.zscaler.com", mozilla_release / "python"),
        ("sitereview.zscaler.com", mozilla_release / "toolkit"),
        ("sitereview.zscaler.com", glean),
        ("use-application-dns.net", application_services),
        ("use-application-dns.net", mozilla_release / "mobile"),
        ("use-application-dns.net", mozilla_release / "modules"),
        ("use-application-dns.net", mozilla_release / "netwerk"),
        ("use-application-dns.net", mozilla_release / "python"),
        ("use-application-dns.net", mozilla_release / "toolkit"),
        ("use-application-dns.net", glean),
        
        ## DoH performance tests
        ("firefox-dns-perf-test.net", application_services),
        ("firefox-dns-perf-test.net", mozilla_release / "mobile"),
        ("firefox-dns-perf-test.net", mozilla_release / "modules"),
        ("firefox-dns-perf-test.net", mozilla_release / "netwerk"),
        ("firefox-dns-perf-test.net", mozilla_release / "python"),
        ("firefox-dns-perf-test.net", mozilla_release / "toolkit"),
        ("firefox-dns-perf-test.net", glean),
        
        ## GeoIP
        ("classify-client.services.mozilla.com", application_services),
        ("classify-client.services.mozilla.com", mozilla_release / "mobile"),
        ("classify-client.services.mozilla.com", mozilla_release / "modules"),
        ("classify-client.services.mozilla.com", mozilla_release / "netwerk"),
        ("classify-client.services.mozilla.com", mozilla_release / "python"),
        ("classify-client.services.mozilla.com", mozilla_release / "toolkit"),
        ("classify-client.services.mozilla.com", glean),
        ("location.services.mozilla.com", application_services),
        ("location.services.mozilla.com", mozilla_release / "mobile"),
        ("location.services.mozilla.com", mozilla_release / "modules"),
        ("location.services.mozilla.com", mozilla_release / "netwerk"),
        ("location.services.mozilla.com", mozilla_release / "python"),
        ("location.services.mozilla.com", mozilla_release / "toolkit"),
        ("location.services.mozilla.com", glean),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", application_services),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", mozilla_release / "mobile"),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", mozilla_release / "modules"),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", mozilla_release / "netwerk"),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", mozilla_release / "python"),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", mozilla_release / "toolkit"),
        ("locprod1-elb-eu-west-1.prod.mozaws.net", glean),
        ("locprod2-elb-us-west-2.prod.mozaws.net", application_services),
        ("locprod2-elb-us-west-2.prod.mozaws.net", mozilla_release / "mobile"),
        ("locprod2-elb-us-west-2.prod.mozaws.net", mozilla_release / "modules"),
        ("locprod2-elb-us-west-2.prod.mozaws.net", mozilla_release / "netwerk"),
        ("locprod2-elb-us-west-2.prod.mozaws.net", mozilla_release / "python"),
        ("locprod2-elb-us-west-2.prod.mozaws.net", mozilla_release / "toolkit"),
        ("locprod2-elb-us-west-2.prod.mozaws.net", glean),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", application_services),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", mozilla_release / "python"),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("nonprod.classify-client.nonprod.webservices.mozgcp.net", glean),
        ("prod.classify-client.prod.webservices.mozgcp.net", application_services),
        ("prod.classify-client.prod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("prod.classify-client.prod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("prod.classify-client.prod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("prod.classify-client.prod.webservices.mozgcp.net", mozilla_release / "python"),
        ("prod.classify-client.prod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("prod.classify-client.prod.webservices.mozgcp.net", glean),
        ("search.r53-2.services.mozilla.com", application_services),
        ("search.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("search.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("search.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("search.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("search.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("search.r53-2.services.mozilla.com", glean),
        ("search.services.mozilla.com", application_services),
        ("search.services.mozilla.com", mozilla_release / "mobile"),
        ("search.services.mozilla.com", mozilla_release / "modules"),
        ("search.services.mozilla.com", mozilla_release / "netwerk"),
        ("search.services.mozilla.com", mozilla_release / "python"),
        ("search.services.mozilla.com", mozilla_release / "toolkit"),
        ("search.services.mozilla.com", glean),
        
        ## Icons
        ("activity-stream-icons.services.mozilla.com", application_services),
        ("activity-stream-icons.services.mozilla.com", mozilla_release / "mobile"),
        ("activity-stream-icons.services.mozilla.com", mozilla_release / "modules"),
        ("activity-stream-icons.services.mozilla.com", mozilla_release / "netwerk"),
        ("activity-stream-icons.services.mozilla.com", mozilla_release / "python"),
        ("activity-stream-icons.services.mozilla.com", mozilla_release / "toolkit"),
        ("activity-stream-icons.services.mozilla.com", glean),
        
        ## MARS
        ("ads.allizom.org", application_services),
        ("ads.allizom.org", mozilla_release / "mobile"),
        ("ads.allizom.org", mozilla_release / "modules"),
        ("ads.allizom.org", mozilla_release / "netwerk"),
        ("ads.allizom.org", mozilla_release / "python"),
        ("ads.allizom.org", mozilla_release / "toolkit"),
        ("ads.allizom.org", glean),
        ("ads.mozilla.org", application_services),
        ("ads.mozilla.org", mozilla_release / "mobile"),
        ("ads.mozilla.org", mozilla_release / "modules"),
        ("ads.mozilla.org", mozilla_release / "netwerk"),
        ("ads.mozilla.org", mozilla_release / "python"),
        ("ads.mozilla.org", mozilla_release / "toolkit"),
        ("ads.mozilla.org", glean),
        ("ads.nonprod.webservices.mozgcp.net", application_services),
        ("ads.nonprod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("ads.nonprod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("ads.nonprod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("ads.nonprod.webservices.mozgcp.net", mozilla_release / "python"),
        ("ads.nonprod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("ads.nonprod.webservices.mozgcp.net", glean),
        ("ads-img.mozilla.org", application_services),
        ("ads-img.mozilla.org", mozilla_release / "mobile"),
        ("ads-img.mozilla.org", mozilla_release / "modules"),
        ("ads-img.mozilla.org", mozilla_release / "netwerk"),
        ("ads-img.mozilla.org", mozilla_release / "python"),
        ("ads-img.mozilla.org", mozilla_release / "toolkit"),
        ("ads-img.mozilla.org", glean),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", application_services),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", mozilla_release / "python"),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("tiles-cdn.prod.ads.prod.webservices.mozgcp.net", glean),
        
        ## Normandy (Experimentation)
        ("normandy.cdn.mozilla.net", application_services),
        ("normandy.cdn.mozilla.net", mozilla_release / "mobile"),
        ("normandy.cdn.mozilla.net", mozilla_release / "modules"),
        ("normandy.cdn.mozilla.net", mozilla_release / "netwerk"),
        ("normandy.cdn.mozilla.net", mozilla_release / "python"),
        ("normandy.cdn.mozilla.net", mozilla_release / "toolkit"),
        ("normandy.cdn.mozilla.net", glean),
        ("normandy.nonprod.cloudops.mozgcp.net", application_services),
        ("normandy.nonprod.cloudops.mozgcp.net", mozilla_release / "mobile"),
        ("normandy.nonprod.cloudops.mozgcp.net", mozilla_release / "modules"),
        ("normandy.nonprod.cloudops.mozgcp.net", mozilla_release / "netwerk"),
        ("normandy.nonprod.cloudops.mozgcp.net", mozilla_release / "python"),
        ("normandy.nonprod.cloudops.mozgcp.net", mozilla_release / "toolkit"),
        ("normandy.nonprod.cloudops.mozgcp.net", glean),
        ("normandy-cdn.services.mozilla.com", application_services),
        ("normandy-cdn.services.mozilla.com", mozilla_release / "mobile"),
        ("normandy-cdn.services.mozilla.com", mozilla_release / "modules"),
        ("normandy-cdn.services.mozilla.com", mozilla_release / "netwerk"),
        ("normandy-cdn.services.mozilla.com", mozilla_release / "python"),
        ("normandy-cdn.services.mozilla.com", mozilla_release / "toolkit"),
        ("normandy-cdn.services.mozilla.com", glean),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", application_services),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", mozilla_release / "mobile"),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", mozilla_release / "modules"),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", mozilla_release / "netwerk"),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", mozilla_release / "python"),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", mozilla_release / "toolkit"),
        ("prod-classifyclient.normandy.prod.cloudops.mozgcp.net", glean),
        
        ## Pocket
        ("firefox-android-home-recommendations.getpocket.com", application_services),
        ("firefox-android-home-recommendations.getpocket.com", mozilla_release / "mobile"),
        ("firefox-android-home-recommendations.getpocket.com", mozilla_release / "modules"),
        ("firefox-android-home-recommendations.getpocket.com", mozilla_release / "netwerk"),
        ("firefox-android-home-recommendations.getpocket.com", mozilla_release / "python"),
        ("firefox-android-home-recommendations.getpocket.com", mozilla_release / "toolkit"),
        ("firefox-android-home-recommendations.getpocket.com", glean),
        ("img-getpocket.cdn.mozilla.net", application_services),
        ("img-getpocket.cdn.mozilla.net", mozilla_release / "mobile"),
        ("img-getpocket.cdn.mozilla.net", mozilla_release / "modules"),
        ("img-getpocket.cdn.mozilla.net", mozilla_release / "netwerk"),
        ("img-getpocket.cdn.mozilla.net", mozilla_release / "python"),
        ("img-getpocket.cdn.mozilla.net", mozilla_release / "toolkit"),
        ("img-getpocket.cdn.mozilla.net", glean),
        ("spocs.getpocket.com", application_services),
        ("spocs.getpocket.com", mozilla_release / "mobile"),
        ("spocs.getpocket.com", mozilla_release / "modules"),
        ("spocs.getpocket.com", mozilla_release / "netwerk"),
        ("spocs.getpocket.com", mozilla_release / "python"),
        ("spocs.getpocket.com", mozilla_release / "toolkit"),
        ("spocs.getpocket.com", glean),
        ("spocs.getpocket.dev", application_services),
        ("spocs.getpocket.dev", mozilla_release / "mobile"),
        ("spocs.getpocket.dev", mozilla_release / "modules"),
        ("spocs.getpocket.dev", mozilla_release / "netwerk"),
        ("spocs.getpocket.dev", mozilla_release / "python"),
        ("spocs.getpocket.dev", mozilla_release / "toolkit"),
        ("spocs.getpocket.dev", glean),
        ("spocs.mozilla.net", application_services),
        ("spocs.mozilla.net", mozilla_release / "mobile"),
        ("spocs.mozilla.net", mozilla_release / "modules"),
        ("spocs.mozilla.net", mozilla_release / "netwerk"),
        ("spocs.mozilla.net", mozilla_release / "python"),
        ("spocs.mozilla.net", mozilla_release / "toolkit"),
        ("spocs.mozilla.net", glean),
        
        ## Remote search configuration
        ("https://firefox.settings.services.allizom.org/v1/buckets/main/collections/search-config/records", mozilla_release / "toolkit/components/search/SearchUtils.sys.mjs"),
        ("https://firefox.settings.services.allizom.org/v1/buckets/main-preview/collections/search-config/records", mozilla_release / "toolkit/components/search/SearchUtils.sys.mjs"),
        ("https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/search-config/records", mozilla_release / "toolkit/components/search/SearchUtils.sys.mjs"),
        ("https://firefox.settings.services.mozilla.com/v1/buckets/main-preview/collections/search-config/records", mozilla_release / "toolkit/components/search/SearchUtils.sys.mjs"),
        
        ## Sentry
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", application_services),
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", mozilla_release / "mobile"),
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", mozilla_release / "modules"),
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", mozilla_release / "netwerk"),
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", mozilla_release / "python"),
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", mozilla_release / "toolkit"),
        ("5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io", glean),
        ("o1069899.ingest.sentry.io", application_services),
        ("o1069899.ingest.sentry.io", mozilla_release / "mobile"),
        ("o1069899.ingest.sentry.io", mozilla_release / "modules"),
        ("o1069899.ingest.sentry.io", mozilla_release / "netwerk"),
        ("o1069899.ingest.sentry.io", mozilla_release / "python"),
        ("o1069899.ingest.sentry.io", mozilla_release / "toolkit"),
        ("o1069899.ingest.sentry.io", glean),
        ("prod.sentry.prod.cloudops.mozgcp.net", application_services),
        ("prod.sentry.prod.cloudops.mozgcp.net", mozilla_release / "mobile"),
        ("prod.sentry.prod.cloudops.mozgcp.net", mozilla_release / "modules"),
        ("prod.sentry.prod.cloudops.mozgcp.net", mozilla_release / "netwerk"),
        ("prod.sentry.prod.cloudops.mozgcp.net", mozilla_release / "python"),
        ("prod.sentry.prod.cloudops.mozgcp.net", mozilla_release / "toolkit"),
        ("prod.sentry.prod.cloudops.mozgcp.net", glean),
        ("sentry.io", application_services),
        ("sentry.io", mozilla_release / "mobile"),
        ("sentry.io", mozilla_release / "modules"),
        ("sentry.io", mozilla_release / "netwerk"),
        ("sentry.io", mozilla_release / "python"),
        ("sentry.io", mozilla_release / "toolkit"),
        ("sentry.io", glean),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", application_services),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", mozilla_release / "mobile"),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", mozilla_release / "modules"),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", mozilla_release / "netwerk"),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", mozilla_release / "python"),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", mozilla_release / "toolkit"),
        ("stage.sentry.nonprod.cloudops.mozgcp.net", glean),
        
        ## Snippets
        ("snippets.allizom.org", application_services),
        ("snippets.allizom.org", mozilla_release / "mobile"),
        ("snippets.allizom.org", mozilla_release / "modules"),
        ("snippets.allizom.org", mozilla_release / "netwerk"),
        ("snippets.allizom.org", mozilla_release / "python"),
        ("snippets.allizom.org", mozilla_release / "toolkit"),
        ("snippets.allizom.org", glean),
        ("snippets.cdn.mozilla.net", application_services),
        ("snippets.cdn.mozilla.net", mozilla_release / "mobile"),
        ("snippets.cdn.mozilla.net", mozilla_release / "modules"),
        ("snippets.cdn.mozilla.net", mozilla_release / "netwerk"),
        ("snippets.cdn.mozilla.net", mozilla_release / "python"),
        ("snippets.cdn.mozilla.net", mozilla_release / "toolkit"),
        ("snippets.cdn.mozilla.net", glean),
        ("snippets.mozilla.com", application_services),
        ("snippets.mozilla.com", mozilla_release / "mobile"),
        ("snippets.mozilla.com", mozilla_release / "modules"),
        ("snippets.mozilla.com", mozilla_release / "netwerk"),
        ("snippets.mozilla.com", mozilla_release / "python"),
        ("snippets.mozilla.com", mozilla_release / "toolkit"),
        ("snippets.mozilla.com", glean),
        ("snippets-prod.frankfurt.moz.works", application_services),
        ("snippets-prod.frankfurt.moz.works", mozilla_release / "mobile"),
        ("snippets-prod.frankfurt.moz.works", mozilla_release / "modules"),
        ("snippets-prod.frankfurt.moz.works", mozilla_release / "netwerk"),
        ("snippets-prod.frankfurt.moz.works", mozilla_release / "python"),
        ("snippets-prod.frankfurt.moz.works", mozilla_release / "toolkit"),
        ("snippets-prod.frankfurt.moz.works", glean),
        ("snippets-prod.moz.works", application_services),
        ("snippets-prod.moz.works", mozilla_release / "mobile"),
        ("snippets-prod.moz.works", mozilla_release / "modules"),
        ("snippets-prod.moz.works", mozilla_release / "netwerk"),
        ("snippets-prod.moz.works", mozilla_release / "python"),
        ("snippets-prod.moz.works", mozilla_release / "toolkit"),
        ("snippets-prod.moz.works", glean),
        ("snippets-prod.oregon-b.moz.works", application_services),
        ("snippets-prod.oregon-b.moz.works", mozilla_release / "mobile"),
        ("snippets-prod.oregon-b.moz.works", mozilla_release / "modules"),
        ("snippets-prod.oregon-b.moz.works", mozilla_release / "netwerk"),
        ("snippets-prod.oregon-b.moz.works", mozilla_release / "python"),
        ("snippets-prod.oregon-b.moz.works", mozilla_release / "toolkit"),
        ("snippets-prod.oregon-b.moz.works", glean),
        ("snippets-stage.moz.works", application_services),
        ("snippets-stage.moz.works", mozilla_release / "mobile"),
        ("snippets-stage.moz.works", mozilla_release / "modules"),
        ("snippets-stage.moz.works", mozilla_release / "netwerk"),
        ("snippets-stage.moz.works", mozilla_release / "python"),
        ("snippets-stage.moz.works", mozilla_release / "toolkit"),
        ("snippets-stage.moz.works", glean),
        ("snippets-stage.oregon-b.moz.works", application_services),
        ("snippets-stage.oregon-b.moz.works", mozilla_release / "mobile"),
        ("snippets-stage.oregon-b.moz.works", mozilla_release / "modules"),
        ("snippets-stage.oregon-b.moz.works", mozilla_release / "netwerk"),
        ("snippets-stage.oregon-b.moz.works", mozilla_release / "python"),
        ("snippets-stage.oregon-b.moz.works", mozilla_release / "toolkit"),
        ("snippets-stage.oregon-b.moz.works", glean),
        
        ## Surveys
        ("survey.mozilla.com", application_services),
        ("survey.mozilla.com", mozilla_release / "mobile"),
        ("survey.mozilla.com", mozilla_release / "modules"),
        ("survey.mozilla.com", mozilla_release / "netwerk"),
        ("survey.mozilla.com", mozilla_release / "python"),
        ("survey.mozilla.com", mozilla_release / "toolkit"),
        ("survey.mozilla.com", glean),
        
        ## Telemetry
        ("coverage.mozilla.org", application_services),
        ("coverage.mozilla.org", mozilla_release / "mobile"),
        ("coverage.mozilla.org", mozilla_release / "modules"),
        ("coverage.mozilla.org", mozilla_release / "netwerk"),
        ("coverage.mozilla.org", mozilla_release / "python"),
        ("coverage.mozilla.org", mozilla_release / "toolkit"),
        ("coverage.mozilla.org", glean),
        ("dap-09-3.api.divviup.org", application_services),
        ("dap-09-3.api.divviup.org", mozilla_release / "mobile"),
        ("dap-09-3.api.divviup.org", mozilla_release / "modules"),
        ("dap-09-3.api.divviup.org", mozilla_release / "netwerk"),
        ("dap-09-3.api.divviup.org", mozilla_release / "python"),
        ("dap-09-3.api.divviup.org", mozilla_release / "toolkit"),
        ("dap-09-3.api.divviup.org", glean),
        ("dap.nonprod.webservices.mozgcp.net", application_services),
        ("dap.nonprod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("dap.nonprod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("dap.nonprod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("dap.nonprod.webservices.mozgcp.net", mozilla_release / "python"),
        ("dap.nonprod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("dap.nonprod.webservices.mozgcp.net", glean),
        ("dap.services.mozilla.com", application_services),
        ("dap.services.mozilla.com", mozilla_release / "mobile"),
        ("dap.services.mozilla.com", mozilla_release / "modules"),
        ("dap.services.mozilla.com", mozilla_release / "netwerk"),
        ("dap.services.mozilla.com", mozilla_release / "python"),
        ("dap.services.mozilla.com", mozilla_release / "toolkit"),
        ("dap.services.mozilla.com", glean),
        ("debug-ping-preview.firebaseapp.com", application_services),
        ("debug-ping-preview.firebaseapp.com", mozilla_release / "mobile"),
        ("debug-ping-preview.firebaseapp.com", mozilla_release / "modules"),
        ("debug-ping-preview.firebaseapp.com", mozilla_release / "netwerk"),
        ("debug-ping-preview.firebaseapp.com", mozilla_release / "python"),
        ("debug-ping-preview.firebaseapp.com", mozilla_release / "toolkit"),
        ("debug-ping-preview.firebaseapp.com", glean),
        ("download-stats.mozilla.org", application_services),
        ("download-stats.mozilla.org", mozilla_release / "mobile"),
        ("download-stats.mozilla.org", mozilla_release / "modules"),
        ("download-stats.mozilla.org", mozilla_release / "netwerk"),
        ("download-stats.mozilla.org", mozilla_release / "python"),
        ("download-stats.mozilla.org", mozilla_release / "toolkit"),
        ("download-stats.mozilla.org", glean),
        ("download-stats.r53-2.services.mozilla.com", application_services),
        ("download-stats.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("download-stats.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("download-stats.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("download-stats.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("download-stats.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("download-stats.r53-2.services.mozilla.com", glean),
        ("fhr.data.mozilla.com", application_services),
        ("fhr.data.mozilla.com", mozilla_release / "mobile"),
        ("fhr.data.mozilla.com", mozilla_release / "modules"),
        ("fhr.data.mozilla.com", mozilla_release / "netwerk"),
        ("fhr.data.mozilla.com", mozilla_release / "python"),
        ("fhr.data.mozilla.com", mozilla_release / "toolkit"),
        ("fhr.data.mozilla.com", glean),
        ("fhr.r53-2.services.mozilla.com", application_services),
        ("fhr.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("fhr.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("fhr.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("fhr.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("fhr.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("fhr.r53-2.services.mozilla.com", glean),
        ("firefox.settings.services.allizom.org", mozilla_release / "toolkit/components/glean"),
        ("firefox.settings.services.allizom.org", mozilla_release / "toolkit/components/telemetry"),
        ("firefox.settings.services.allizom.org", glean),
        ("firefox.settings.services.mozilla.com", mozilla_release / "toolkit/components/glean"),
        ("firefox.settings.services.mozilla.com", mozilla_release / "toolkit/components/telemetry"),
        ("firefox.settings.services.mozilla.com", glean),
        ("incoming.glean.example.com", application_services),
        ("incoming.glean.example.com", mozilla_release / "mobile"),
        ("incoming.glean.example.com", mozilla_release / "modules"),
        ("incoming.glean.example.com", mozilla_release / "netwerk"),
        ("incoming.glean.example.com", mozilla_release / "python"),
        ("incoming.glean.example.com", mozilla_release / "toolkit"),
        ("incoming.glean.example.com", glean),
        ("incoming.telemetry.mozilla.org", application_services),
        ("incoming.telemetry.mozilla.org", mozilla_release / "mobile"),
        ("incoming.telemetry.mozilla.org", mozilla_release / "modules"),
        ("incoming.telemetry.mozilla.org", mozilla_release / "netwerk"),
        ("incoming.telemetry.mozilla.org", mozilla_release / "python"),
        ("incoming.telemetry.mozilla.org", mozilla_release / "toolkit"),
        ("incoming.telemetry.mozilla.org", glean),
        ("incoming.thunderbird.net", application_services),
        ("incoming.thunderbird.net", mozilla_release / "mobile"),
        ("incoming.thunderbird.net", mozilla_release / "modules"),
        ("incoming.thunderbird.net", mozilla_release / "netwerk"),
        ("incoming.thunderbird.net", mozilla_release / "python"),
        ("incoming.thunderbird.net", mozilla_release / "toolkit"),
        ("incoming.thunderbird.net", glean),
        ("incoming-telemetry.thunderbird.net", application_services),
        ("incoming-telemetry.thunderbird.net", mozilla_release / "mobile"),
        ("incoming-telemetry.thunderbird.net", mozilla_release / "modules"),
        ("incoming-telemetry.thunderbird.net", mozilla_release / "netwerk"),
        ("incoming-telemetry.thunderbird.net", mozilla_release / "python"),
        ("incoming-telemetry.thunderbird.net", mozilla_release / "toolkit"),
        ("incoming-telemetry.thunderbird.net", glean),
        ("mozilla-ohttp.fastly-edge.com", mozilla_release / "toolkit/components/glean"),
        ("mozilla-ohttp.fastly-edge.com", mozilla_release / "toolkit/components/telemetry"),
        ("mozilla-ohttp.fastly-edge.com", glean),
        ("prod.dap.prod.webservices.mozgcp.net", application_services),
        ("prod.dap.prod.webservices.mozgcp.net", mozilla_release / "mobile"),
        ("prod.dap.prod.webservices.mozgcp.net", mozilla_release / "modules"),
        ("prod.dap.prod.webservices.mozgcp.net", mozilla_release / "netwerk"),
        ("prod.dap.prod.webservices.mozgcp.net", mozilla_release / "python"),
        ("prod.dap.prod.webservices.mozgcp.net", mozilla_release / "toolkit"),
        ("prod.dap.prod.webservices.mozgcp.net", glean),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", application_services),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", mozilla_release / "mobile"),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", mozilla_release / "modules"),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", mozilla_release / "netwerk"),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", mozilla_release / "python"),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", mozilla_release / "toolkit"),
        ("prod.data-ingestion.prod.dataops.mozgcp.net", glean),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", application_services),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", mozilla_release / "mobile"),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", mozilla_release / "modules"),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", mozilla_release / "netwerk"),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", mozilla_release / "python"),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", mozilla_release / "toolkit"),
        ("prod.ingestion-edge.prod.dataops.mozgcp.net", glean),
        ("prod.ohttp-gateway.prod.webservices.mozgcp.net", mozilla_release / "toolkit/components/glean"),
        ("prod.ohttp-gateway.prod.webservices.mozgcp.net", mozilla_release / "toolkit/components/telemetry"),
        ("prod.ohttp-gateway.prod.webservices.mozgcp.net", glean),
        ("self-repair.mozilla.org", application_services),
        ("self-repair.mozilla.org", mozilla_release / "mobile"),
        ("self-repair.mozilla.org", mozilla_release / "modules"),
        ("self-repair.mozilla.org", mozilla_release / "netwerk"),
        ("self-repair.mozilla.org", mozilla_release / "python"),
        ("self-repair.mozilla.org", mozilla_release / "toolkit"),
        ("self-repair.mozilla.org", glean),
        ("self-repair.r53-2.services.mozilla.com", application_services),
        ("self-repair.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("self-repair.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("self-repair.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("self-repair.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("self-repair.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("self-repair.r53-2.services.mozilla.com", glean),
        ("telemetry-coverage.mozilla.org", application_services),
        ("telemetry-coverage.mozilla.org", mozilla_release / "mobile"),
        ("telemetry-coverage.mozilla.org", mozilla_release / "modules"),
        ("telemetry-coverage.mozilla.org", mozilla_release / "netwerk"),
        ("telemetry-coverage.mozilla.org", mozilla_release / "python"),
        ("telemetry-coverage.mozilla.org", mozilla_release / "toolkit"),
        ("telemetry-coverage.mozilla.org", glean),
        ("telemetry-coverage.r53-2.services.mozilla.com", application_services),
        ("telemetry-coverage.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("telemetry-coverage.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("telemetry-coverage.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("telemetry-coverage.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("telemetry-coverage.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("telemetry-coverage.r53-2.services.mozilla.com", glean),
        ("telemetry-experiment.cdn.mozilla.net", application_services),
        ("telemetry-experiment.cdn.mozilla.net", mozilla_release / "mobile"),
        ("telemetry-experiment.cdn.mozilla.net", mozilla_release / "modules"),
        ("telemetry-experiment.cdn.mozilla.net", mozilla_release / "netwerk"),
        ("telemetry-experiment.cdn.mozilla.net", mozilla_release / "python"),
        ("telemetry-experiment.cdn.mozilla.net", mozilla_release / "toolkit"),
        ("telemetry-experiment.cdn.mozilla.net", glean),
        ("telemetry-incoming.r53-2.services.mozilla.com", application_services),
        ("telemetry-incoming.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("telemetry-incoming.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("telemetry-incoming.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("telemetry-incoming.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("telemetry-incoming.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("telemetry-incoming.r53-2.services.mozilla.com", glean),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", application_services),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("telemetry-incoming-a.r53-2.services.mozilla.com", glean),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", application_services),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", mozilla_release / "mobile"),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", mozilla_release / "modules"),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", mozilla_release / "netwerk"),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", mozilla_release / "python"),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", mozilla_release / "toolkit"),
        ("telemetry-incoming-b.r53-2.services.mozilla.com", glean),
        
        ## Top Sites
        ("topsites.services.mozilla.com", application_services),
        ("topsites.services.mozilla.com", mozilla_release / "mobile"),
        ("topsites.services.mozilla.com", mozilla_release / "modules"),
        ("topsites.services.mozilla.com", mozilla_release / "netwerk"),
        ("topsites.services.mozilla.com", mozilla_release / "python"),
        ("topsites.services.mozilla.com", mozilla_release / "toolkit"),
        ("topsites.services.mozilla.com", glean),
        # fmt:on
    ]

    items.sort(key=itemgetter(1))

    return {
        path: [endpoint for endpoint, _ in group]
        for path, group in groupby(items, key=itemgetter(1))
    }
