#!/bin/bash

# This file is expected to be executed in GitLab CI
# DO NOT executed this manually!

set -euo pipefail

# Set-up our environment
if [[ -z "${IRONFOX_SET_ENVS+x}" ]]; then
    bash -x "$(realpath $(dirname "$0"))/env.sh"
fi
source "$(realpath $(dirname "$0"))/env.sh"

readonly GENERIC_PACKAGES_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"

function upload_to_package_registry() {
    local readonly upload_file="$1"
    local readonly upload_package_name="$2"
    local readonly upload_file_name="$(basename "${upload_file}")"
    curl ${IRONFOX_CURL_FLAGS} --header "PRIVATE-TOKEN: ${GITLAB_CI_API_TOKEN}" \
        --upload-file "${upload_file}" \
        "${GENERIC_PACKAGES_URL}/${upload_package_name}/${IRONFOX_VERSION}/${upload_file_name}"
}

# Extract compressed artifacts
mkdir -p "${IRONFOX_ARTIFACTS}"
for archive in "${IRONFOX_ARTIFACTS}"/*.tar.xz; do
    [ -f "${archive}" ] || continue
    echo "Extracting ${archive}"
    "${IRONFOX_TAR}" xvJf "${archive}" -C "${IRONFOX_ARTIFACTS}"
done

readonly BUILD_DIR="${CI_PROJECT_DIR}/build"

mkdir -vp "${BUILD_DIR}"

readonly RELEASE_NOTES_FILE="${BUILD_DIR}/release-notes.md"
readonly CHECKSUMS_FILE="${BUILD_DIR}/asset-checksums.txt"
readonly RELEASE_FILE="${BUILD_DIR}/release.yml"

echo -n "" > "${RELEASE_NOTES_FILE}"
echo -n "" > "${CHECKSUMS_FILE}"

declare -a assets
function upload_asset() {
    local readonly asset_package_name="$1"
    local readonly asset_file="$2"
    local readonly asset_file_name="$(basename "${asset_file}")"

    echo "\`${asset_file_name}\`: " >> "${CHECKSUMS_FILE}"
    echo "\`\`\`sh" >> "${CHECKSUMS_FILE}"
    echo "$(sha512sum -b "${asset_file}" | cut -d ' ' -f 1)" >> "${CHECKSUMS_FILE}"
    echo "\`\`\`sh" >> "${CHECKSUMS_FILE}"
    echo '' >> "${CHECKSUMS_FILE}"
    upload_to_package_registry "${asset_file}" "${asset_package_name}"
    assets+=("{\"name\": \"${asset_file_name}\",\"url\": \"${GENERIC_PACKAGES_URL}/${asset_package_name}/${IRONFOX_VERSION}/${asset_file_name}\",\"link_type\": \"package\",\"direct_asset_path\": \"/${asset_file_name}\"}")
}

# Upload packages to package registry
readonly package_name_apk='apk'
readonly package_name_apkset='apkset'

for apk in "${IRONFOX_APK_ARTIFACTS}"/*.apk; do
    upload_asset "${package_name_apk}" "${apk}"
done

for apks in "${IRONFOX_APKS_ARTIFACTS}"/*.apks; do
    upload_asset "${package_name_apkset}" "${apks}"
done

{
    readonly changelog_file="${CI_PROJECT_DIR}/changelogs/${IRONFOX_VERSION}.md"
    if [[ -f "${changelog_file}" ]]; then
        cat "${changelog_file}"
    fi

    echo "# IronFox ${IRONFOX_VERSION}"
    echo '____'
    echo ''

    echo '## Changes'
    echo ''
    echo '- '
    echo ''

    echo '## App Verification'
    echo "To verify the integrity/authenticity of your IronFox installation, in addition to [the checksums](#checksums) provided below, we highly recommend using [\`AppVerifier\`](https://github.com/soupslurpr/AppVerifier):"
    echo ''
    echo "Package ID: \`org.ironfoxoss.ironfox\`"
    echo ''
    echo 'SHA256 hash of signing certificate:'
    echo "\`\`\`sh"
    echo 'C5:E2:91:B5:A5:71:F9:C8:CD:9A:97:99:C2:C9:4E:02:EC:97:03:94:88:93:F2:CA:75:6D:67:B9:42:04:F9:04'
    echo "\`\`\`"
    echo ""

    echo '## Checksums'
    echo ''
    cat ${CHECKSUMS_FILE}
    echo ''

    echo '---'
    echo "_This release was automatically generated by the CI/CD pipeline ([view pipeline](${CI_JOB_URL})) and is guaranteed to be generated from commit [${CI_COMMIT_SHORT_SHA}](${CI_PROJECT_URL}/-/tree/${CI_COMMIT_SHA})._"
    echo ''
} >>"${RELEASE_NOTES_FILE}"

{
    echo "---"
    echo "name: IronFox v${IRONFOX_VERSION}"
    echo "tag-name: v${IRONFOX_VERSION}"
    echo "description: |"
    "${IRONFOX_AWK}" '{print "  " $0}' <"${RELEASE_NOTES_FILE}"
    echo "assets-link:"
    for asset in "${assets[@]}"; do
        echo "  - '${asset}'"
    done
} >"${RELEASE_FILE}"
