# IronFox build target environment variables

## This is used for configuring the target build/architecture/type.

## CAUTION: Do NOT source this directly!
## Source 'env_target.sh' instead.

# ARM64 constants
export IRONFOX_TARGET_ABI_ARM64='arm64-v8a'
export IRONFOX_TARGET_ARCH_MOZ_ARM64='arm64'
export IRONFOX_TARGET_PRETTY_ARM64='ARM64'
export IRONFOX_TARGET_RUST_ARM64='arm64'

# ARM constants
export IRONFOX_TARGET_ABI_ARM='armeabi-v7a'
export IRONFOX_TARGET_ARCH_MOZ_ARM='arm'
export IRONFOX_TARGET_PRETTY_ARM='ARM'
export IRONFOX_TARGET_RUST_ARM='arm'

# x86_64 constants
export IRONFOX_TARGET_ABI_X86_64='x86_64'
export IRONFOX_TARGET_ARCH_MOZ_X86_64='x86_64'
export IRONFOX_TARGET_PRETTY_X86_64='x86_64'
export IRONFOX_TARGET_RUST_X86_64='x86_64'

# Bundle constants
export IRONFOX_TARGET_ABI_BUNDLE='arm64-v8a", "armeabi-v7a", "x86_64'
export IRONFOX_TARGET_ARCH_MOZ_BUNDLE='bundle'
export IRONFOX_TARGET_PRETTY_BUNDLE='Bundle'
export IRONFOX_TARGET_RUST_BUNDLE='arm64,arm,x86_64'

if [[ "${IRONFOX_TARGET_ARCH}" == 'arm64' ]]; then
    export IRONFOX_TARGET_ABI="${IRONFOX_TARGET_ABI_ARM64}"
    export IRONFOX_TARGET_ARCH_MOZ="${IRONFOX_TARGET_ARCH_MOZ_ARM64}"
    export IRONFOX_TARGET_PRETTY="${IRONFOX_TARGET_PRETTY_ARM64}"
    export IRONFOX_TARGET_RUST="${IRONFOX_TARGET_RUST_ARM64}"
elif [[ "${IRONFOX_TARGET_ARCH}" == 'arm' ]]; then
    export IRONFOX_TARGET_ABI="${IRONFOX_TARGET_ABI_ARM}"
    export IRONFOX_TARGET_ARCH_MOZ="${IRONFOX_TARGET_ARCH_MOZ_ARM}"
    export IRONFOX_TARGET_PRETTY="${IRONFOX_TARGET_PRETTY_ARM}"
    export IRONFOX_TARGET_RUST="${IRONFOX_TARGET_RUST_ARM}"
elif [[ "${IRONFOX_TARGET_ARCH}" == 'x86_64' ]]; then
    export IRONFOX_TARGET_ABI="${IRONFOX_TARGET_ABI_X86_64}"
    export IRONFOX_TARGET_ARCH_MOZ="${IRONFOX_TARGET_ARCH_MOZ_X86_64}"
    export IRONFOX_TARGET_PRETTY="${IRONFOX_TARGET_PRETTY_X86_64}"
    export IRONFOX_TARGET_RUST="${IRONFOX_TARGET_RUST_X86_64}"
elif [[ "${IRONFOX_TARGET_ARCH}" == 'bundle' ]]; then
    export IRONFOX_TARGET_ABI="${IRONFOX_TARGET_ABI_BUNDLE}"
    export IRONFOX_TARGET_ARCH_MOZ="${IRONFOX_TARGET_ARCH_MOZ_BUNDLE}"
    export IRONFOX_TARGET_PRETTY="${IRONFOX_TARGET_PRETTY_BUNDLE}"
    export IRONFOX_TARGET_RUST="${IRONFOX_TARGET_RUST_BUNDLE}"
fi
