#!/bin/bash
# shellcheck disable=SC2034

# Sources
APPSERVICES_VERSION="release-v145"
FIREFOX_VERSION="145.0.1"
FIREFOX_RELEASE_TAG="FIREFOX-ANDROID_${FIREFOX_VERSION//./_}_RELEASE"
#FIREFOX_RELEASE_TAG="FIREFOX-ANDROID_${FIREFOX_VERSION//./_}_BUILD1"
#FIREFOX_RELEASE_TAG="FIREFOX-ANDROID_${FIREFOX_VERSION//./_}_BUILD2"
FIREFOX_RELEASE_PATH="releases/${FIREFOX_VERSION}"
GLEAN_VERSION="v65.2.3"

IRONFOX_VERSION="${FIREFOX_VERSION}"

## Dependencies
GMSCORE_VERSION="v0.3.10.250932"
PHOENIX_VERSION="2025.11.07.1"
UNIFIEDPUSH_VERSION="3.1.2"
WASI_VERSION="wasi-sdk-20"

# Tools
BUNDLETOOL_VERSION="1.18.2"
CBINDGEN_VERSION="0.29.0"
#RUST_MAJOR_VERSION="1.91"
#RUST_VERSION="${RUST_MAJOR_VERSION}.0"
RUST_MAJOR_VERSION="1.91.1"
RUST_VERSION="${RUST_MAJOR_VERSION}"
UNIFFI_VERSION="0.29.0"
UNIFFI_REVISION="${UNIFFI_VERSION}-047359"

# Android SDK
BUILDTOOLS_VERSION="36.0.0"
NDK_REVISION="28.1.13356709"
SDK_REVISION="13114758"

# Configuration
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_SH="${ROOTDIR}/scripts/env_local.sh"
BUILDDIR="${ROOTDIR}/build"
PATCHDIR="${ROOTDIR}/patches"
GECKODIR="${ROOTDIR}/gecko"
ANDROID_COMPONENTS="${GECKODIR}/mobile/android/android-components"
APPSERVICESDIR="${ROOTDIR}/application-services"
BUNDLETOOLDIR="$BUILDDIR/bundletool"
FENIX="${GECKODIR}/mobile/android/fenix"
GLEANDIR="${ROOTDIR}/glean"
GMSCOREDIR="${ROOTDIR}/gmscore"
UNIFFIDIR="${ROOTDIR}/uniffi"
WASISDKDIR="${ROOTDIR}/wasi-sdk"

# Use GNU Sed on macOS instead of the built-in sed, due to differences in syntax
if [[ "$OSTYPE" == "darwin"* ]]; then
    SED=gsed
else
    SED=sed
fi
