#!/bin/bash
# shellcheck disable=SC2034

# Sources
FIREFOX_VERSION="139.0"
FIREFOX_RELEASE_TAG="FIREFOX-ANDROID_${FIREFOX_VERSION//./_}_RELEASE"
FIREFOX_RELEASE_PATH="releases/${FIREFOX_VERSION}"
#FIREFOX_RC_BUILD_NAME="build1"
#FIREFOX_RELEASE_TAG="FIREFOX_${FIREFOX_VERSION//./_}_${FIREFOX_RC_BUILD_NAME^^}"
#FIREFOX_RELEASE_PATH="candidates/${FIREFOX_VERSION}-candidates/${FIREFOX_RC_BUILD_NAME}"
WASI_TAG="wasi-sdk-20"
GLEAN_TAG="v64.3.1"
GMSCORE_TAG="v0.3.7.250932"
APPSERVICES_TAG="release-v140"

# Tools
BUNDLETOOL_TAG="1.18.0"
RUST_VERSION="1.83.0"
CBINDGEN_VERSION="0.28.0"

# Configuration
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_SH="${ROOTDIR}/scripts/env_local.sh"
BUILDDIR="${ROOTDIR}/build"
PATCHDIR="${ROOTDIR}/patches"
GECKODIR="${ROOTDIR}/gecko"
GLEANDIR="${ROOTDIR}/glean"
APPSERVICESDIR="${ROOTDIR}/appservices"
GMSCOREDIR="${ROOTDIR}/gmscore"
WASISDKDIR="${ROOTDIR}/wasi-sdk"
ANDROID_COMPONENTS="${GECKODIR}/mobile/android/android-components"
FENIX="${GECKODIR}/mobile/android/fenix"
